import { NotificationProvider } from '@web3uikit/core'
import Head from 'next/head'
import { MoralisProvider } from 'react-moralis'
import Header from '../components/Header'
import '../styles/globals.css'
import { DataProvider } from '../Contexts/DataContext'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>FreeWill Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MoralisProvider initializeOnMount={false}>
        <NotificationProvider>
          <DataProvider>
            <Header />
            <Component {...pageProps} />
          </DataProvider>
        </NotificationProvider>
      </MoralisProvider>
    </>
  )
}

export default MyApp
